#!/bin/sh
set -eu

PREFIX="/usr/lib/tpu-gdb-proxy"
DEVICE_TYPE="${1:-1690}"

case "${DEVICE_TYPE}" in
    1690) NUM_CORE=8 ;;
    1690e|cv84x6) NUM_CORE=4 ;;
    *)
        echo "install: unsupported device type: ${DEVICE_TYPE} (expect 1690|1690e|cv84x6)" >&2
        exit 1
        ;;
esac

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TOOL_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

# --- Python 与 import 路径（WorkingDirectory 与此一致） ---
install -d "${PREFIX}"
install -m 0644 \
    "${TOOL_DIR}/proxy_fast.py" \
    "${TOOL_DIR}/rcmd.py" \
    "${TOOL_DIR}/transport.py" \
    "${PREFIX}/"

# --- monitor script 脚本目录（白名单脚本放这里）---
install -d "${PREFIX}/scripts"
if [ -d "${TOOL_DIR}/scripts" ]; then
    for f in "${TOOL_DIR}/scripts/"*; do
        [ -e "$f" ] || continue
        base=$(basename "$f")
        case "$base" in
            *.sh|*.py)
                install -m 0755 "$f" "${PREFIX}/scripts/$base"
                ;;
            *)
                install -m 0644 "$f" "${PREFIX}/scripts/$base"
                ;;
        esac
    done
fi

# --- systemd unit ---
install -d "/etc/systemd/system"
install -m 0644 "${SCRIPT_DIR}/linux/systemd/gdb-proxy@.service" \
    "/etc/systemd/system/gdb-proxy@.service"
install -m 0644 "${SCRIPT_DIR}/linux/systemd/gdb-proxy-refresh.service" \
    "/etc/systemd/system/gdb-proxy-refresh.service"

# 升级：移除旧单实例 unit / 旧 default
rm -f "/etc/systemd/system/gdb-proxy.service"
rm -f "/etc/default/gdb-proxy-0" "/etc/default/gdb-proxy-1"

# --- 运行时可调参数（全实例统一）---
install -d "/etc/default"
cat > "/etc/default/gdb-proxy" <<EOF
# /etc/default/gdb-proxy - generated by install.sh (${DEVICE_TYPE})
GDB_PROXY_LISTEN_HOST=0.0.0.0
GDB_PROXY_NUM_CORE=${NUM_CORE}
EOF

# --- modprobe 装/卸 sgcard 时自动 start/stop 服务 ---
if [ "${DEVICE_TYPE}" != "cv84x6" ]; then
    install -d "/etc/modprobe.d"
    install -m 0644 "${SCRIPT_DIR}/linux/modprobe.d/sgcard-gdb-proxy.conf" \
        "/etc/modprobe.d/sgcard-gdb-proxy.conf"
fi

# --- udev：节点出现时的兜底；reload-rules 后才保证立刻生效 ---
install -d "/etc/udev/rules.d"
install -m 0644 "${SCRIPT_DIR}/linux/udev/99-gdb-proxy-sgcard.rules" \
    "/etc/udev/rules.d/99-gdb-proxy-sgcard.rules"

cat <<EOF
[install] done. PREFIX=${PREFIX} DEVICE_TYPE=${DEVICE_TYPE} NUM_CORE=${NUM_CORE}

安装完成后请手动执行如下命令后，重启驱动模块：

  sudo systemctl daemon-reload
  sudo udevadm control --reload-rules

执行后可手动检查 sudo systemctl status "gdb-proxy@*" 命令是否有输出。

EOF
